version: "3"

services:

    dispatcher:
        build: .
        ports:
            - 80:80
        networks:
            - web
            
    site1:
        build: ./site1/
        tty: true
        entrypoint:
            - /bin/bash
            - /run.sh
        ports:
          - "81:81"
        networks:
            - web

networks:
    web: