version: "3"

services:

    dispatcher:
        build: .
        ports:
            - 80:80
        networks:
            - web
            
    site1:
        build: ./site1/
        networks:
            - web

networks:
    web: